---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv-matheusaluno-claim
  namespace: matheusaluno
  labels:
    type: local
spec:
  storageClassName: "default-storage-class"
  volumeName: project2-pv2-matheusaluno
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: cloudcomp-pod-matheus
  namespace: matheusaluno
  labels:
    app: cloudcomp-pod-matheus
spec:
  volumes:
    - name: project2-matheus-storage
      persistentVolumeClaim:
        claimName: project2-pv-matheusaluno-claim
  containers:
    - name: cloudcomp-recommendation
      image: biomasdev/cloudcomp-recommendation:0.23
      ports:
        - containerPort: 5000
          name: http-predict
      volumeMounts:
        - mountPath: /data
          name: project2-matheus-storage
      env:
        - name: REACT_APP_FRONTEND_PORT
          value: "30242"
    - name: cloudcomp-frontend
      image: biomasdev/cloudcomp-frontend:0.23
      ports:
        - containerPort: 3000
          name: http-frontend
      env:
        - name: REACT_APP_RECOMMENDATION_PORT
          value: "30241"

  initContainers:
    - name: cloudcomp-mltrain
      image: biomasdev/cloudcomp-mltrain:0.23
      volumeMounts:
        - mountPath: /data
          name: project2-matheus-storage
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: matheusaluno
spec:
  selector:
    app: cloudcomp-pod-matheus
  ports:
    - protocol: TCP
      name: http-recommendation-svc
      port: 5000
      targetPort: http-predict
      nodePort: 30241
    - protocol: TCP
      name: http-frontend-svc
      port: 3000
      targetPort: http-frontend
      nodePort: 30242
  type: NodePort
