---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv-matheusaluno-claim
  namespace: matheusaluno
  labels:
    type: local
spec:
  storageClassName: "default-storage-class"
  volumeName: project2-pv2-matheusaluno
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: presyncfiles
  namespace: matheusaluno
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudcomp-recommendation-presync
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: project2-matheus-storage
          persistentVolumeClaim:
            claimName: project2-pv-matheusaluno-claim
        - name: git-ssh
          secret:
            secretName: git-ssh-key
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
      containers:
        - name: sync-files
          image: alpine/git
          command:
            - sh
            - -c
            - |
              mkdir -p ~/.ssh
              cp /etc/git-ssh/ssh-privatekey ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone git@github.com:biomasdev/cloudcomp-argocd.git /tmp/repo
              cp /tmp/repo/recommendation/spotify_dataset.csv /data/spotify_dataset.csv
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
            - name: git-ssh
              mountPath: /etc/git-ssh

        - name: cloudcomp-mltrain
          image: biomasdev/cloudcomp-mltrain:0.28
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
