apiVersion: batch/v1
kind: Job
metadata:
  generateName: presyncfiles
  namespace: matheusalves
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudcomp-recommendation-presync
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: project2-matheus-storage
          persistentVolumeClaim:
            claimName: project2-pv-matheusalves-claim
      initContainers:
        - name: sync-files
          image: alpine/git
          command:
            - sh
            - -c
            - |
              git clone https://github.com/biomasdev/cloudcomp-argocd.git /tmp/repo
              cp /tmp/repo/recommendation/dataset/spotify_dataset.csv /data/spotify_dataset.csv
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
      containers:
        - name: cloudcomp-mltrain
          image: biomasdev/cloudcomp-mltrain:0.46
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
          resources:
            requests:
              memory: "2G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "500m"
