apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcomp-recommendation-deployment
  namespace: matheusaluno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcomp-recommendation
  template:
    metadata:
      labels:
        app: cloudcomp-recommendation
    spec:
      volumes:
        - name: project2-matheus-storage
          persistentVolumeClaim:
            claimName: project2-pv-matheusaluno-claim
        - name: git-ssh
          secret:
            secretName: git-ssh-key
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
      initContainers:
        - name: sync-files
          image: alpine/git
          command:
            - sh
            - -c
            - |
              mkdir -p ~/.ssh
              cp /etc/git-ssh/ssh-privatekey ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone git@github.com:biomasdev/cloudcomp-argocd.git /tmp/repo
              cp /tmp/repo/recommendation/spotify_dataset.csv /data/spotify_dataset.csv
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
            - name: git-ssh
              mountPath: /etc/git-ssh

        - name: cloudcomp-mltrain
          image: biomasdev/cloudcomp-mltrain:0.24
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage

      containers:
        - name: cloudcomp-recommendation
          image: biomasdev/cloudcomp-recommendation:0.24
          ports:
            - containerPort: 5000
              name: http-predict
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
          env:
            - name: REACT_APP_FRONTEND_PORT
              value: "30242"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
