apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcomp-recommendation-deployment
  namespace: matheusalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcomp-recommendation
  template:
    metadata:
      labels:
        app: cloudcomp-recommendation
    spec:
      volumes:
        - name: project2-matheus-storage
          persistentVolumeClaim:
            claimName: project2-pv-matheusalves-claim

      containers:
        - name: cloudcomp-recommendation
          image: biomasdev/cloudcomp-recommendation:0.60
          ports:
            - containerPort: 5000
              name: http-predict
          volumeMounts:
            - mountPath: /data
              name: project2-matheus-storage
          env:
            - name: REACT_APP_FRONTEND_PORT
              value: "30242"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
