apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcomp-frontend-deployment
  namespace: matheusalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcomp-frontend
  template:
    metadata:
      labels:
        app: cloudcomp-frontend
    spec:
      containers:
        - name: cloudcomp-frontend
          image: biomasdev/cloudcomp-frontend:0.57
          ports:
            - containerPort: 3000
              name: http-frontend
          env:
            - name: REACT_APP_RECOMMENDATION_PORT
              value: "52052"
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "1G"
              cpu: "1"
