apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv-matheusaluno-claim
  namespace: matheusaluno
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    type: local
spec:
  storageClassName: "default-storage-class"
  volumeName: project2-pv2-matheusaluno
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
