apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv-matheusalves-claim
  namespace: matheusalves
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    type: local
spec:
  storageClassName: "default-storage-class-matheusalves"
  volumeName: project2-pv2-matheusalves
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
