apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-backend
  namespace: matheusalves
spec:
  selector:
    app: cloudcomp-recommendation
  ports:
    - protocol: TCP
      name: http-predict
      port: 5000
      targetPort: 5000
      nodePort: 52052
  type: NodePort
