apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-frontend
  namespace: matheusalves
spec:
  selector:
    app: cloudcomp-frontend
  ports:
    - protocol: TCP
      name: http-frontend
      port: 3000
      targetPort: 3000
      nodePort: 30242
  type: NodePort
